name: sonarcloud

on:
  push:
    branches: ['master']
  pull_request:
    branches: ['master']

jobs:
  sonarcloud:
    runs-on: ubuntu-latest
    environment: Tests

    steps:
      - name: Code Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Nodejs Config
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'
          cache: npm

      - name: Install Dependencies
        run: npm ci

      - name: Run tests + coverage
        run: npm test

      - name: Get project version
        id: package-version
        run: echo "version=$(node -p "require('./package.json').version")" >> $GITHUB_OUTPUT

      - name: SonarCloud Scan
        uses: SonarSource/sonarcloud-github-action@v3
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        with:
          args: >
            -Dsonar.projectKey=ArturKioshi_ES2_2025-2_hackathon-starter
            -Dsonar.organization=arturkioshi
            -Dsonar.javascript.lcov.reportPaths=coverage/lcov.info
            -Dsonar.sources=.
            -Dsonar.tests=test
            -Dsonar.exclusions=**/*.test.js,**/test/**,coverage/**,node_modules/**
            -Dsonar.branch.name=master
